import type { Meta, StoryObj } from '@storybook/react';
import Input from './Input';
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const Default: Story;
export declare const WithHelperText: Story;
export declare const WithError: Story;
export declare const Required: Story;
export declare const Disabled: Story;
export declare const WithIcon: Story;
export declare const Variants: Story;
export declare const Sizes: Story;
export declare const Animated: Story;
export declare const FullWidth: Story;
