import type { Meta, StoryObj } from '@storybook/react';
import Button from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Outline: Story;
export declare const Ghost: Story;
export declare const Danger: Story;
export declare const Sizes: Story;
export declare const WithIcon: Story;
export declare const Loading: Story;
export declare const FullWidth: Story;
export declare const Animated: Story;
export declare const Disabled: Story;
